### ISSUE TITLE
Request - add logout()

### ISSUE THREAD

**Issue by tkrevh** [pboulch/nativescript-google-login#1]
Thanks for this awesome plugin 👍 
Please, would it be possible to add also a logout function?

Issue is, if user logs in with Google once, they can not log in with Google using another account - the login dialog with account selection is never presented to them again.

**Comment by pboulch** [comment]
Merged and published (v1.3.0)

**Comment by gambheera** [comment]
@tkrevh What is the nativescript version that you are using?

**Comment by tkrevh** [comment]
@gambheera 6.2
